# Generated by Django 4.2 on 2023-04-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.CASCADE, to='takedata.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.CASCADE, to='takedata.semester')),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.CASCADE, to='takedata.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('approved', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, default='', max_length=10)),
                ('marks', models.FloatField(blank=True, default=1)),
                ('type', models.CharField(blank=True, choices=[('MCQs', 'MCQs'), ('Fill in the Blanks', 'Fill in the Blanks'), ('True or False', 'True or False')], default='MCQs', max_length=50)),
                ('topic', models.ForeignKey(db_column='topic', on_delete=django.db.models.deletion.CASCADE, related_name='topic_name', to='takedata.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=500, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takedata.question')),
            ],
        ),
    ]
