# Generated by Django 4.2 on 2023-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.JSONField(blank=True, default=dict)),
                ('time', models.DateTimeField(blank=True, default=None)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('questions', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(default=dict, verbose_name='Test Results')),
                ('score', models.JSONField(default=dict)),
                ('modified', models.JSONField(blank=True, default=dict)),
                ('test_time', models.FloatField(blank=True, default=5)),
                ('topic', models.CharField(blank=True, default='', max_length=10)),
                ('by', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
